#!/bin/bash

# Demo 4: CI/CD Pipeline Overview
# This script explains the GitHub Actions pipelines

set -e

cd "$(dirname "$0")/../.."

echo "=========================================="
echo "🎯 DEMO 4: CI/CD Pipeline Overview"
echo "=========================================="
echo ""
echo "This demonstrates GitHub Actions workflows for automated deployment:"
echo ""

# Check if GitHub workflows exist
workflow_dir=".github/workflows"
if [[ ! -d "$workflow_dir" ]]; then
  echo "⚠️  Workflows not yet created."
  echo "   This demo explains what the pipelines will do."
  echo ""
fi

echo "📁 Workflow Structure:"
tree -L 1 .github/workflows 2>/dev/null || echo "  (will create: ci.yml, cd-iaas.yml, cd-paas.yml, cd-saas.yml)"
echo ""

echo "=========================================="
echo "🔄 Pipeline Stages"
echo "=========================================="
echo ""

echo "1️⃣  Continuous Integration (ci.yml)"
echo "   Trigger: Pull request to main/develop"
echo ""
echo "   Steps:"
echo "     a) Checkout code"
echo "     b) Setup Node.js (cache npm)"
echo "     c) Type check: tsc --noEmit"
echo "     d) Lint: eslint src/"
echo "     e) Test: jest --coverage"
echo "     f) Build: npm run build (backend) + npm run build (frontend)"
echo "     g) Build Docker images (backend & frontend)"
echo "     h) Security scan (Snyk/Trivy)"
echo "     i) Upload artifacts: Docker images, coverage reports"
echo ""
echo "   Success: ✅ Green check on PR"
echo "   Failure: ❌ Red X, PR blocked from merge"
echo ""

echo "2️⃣  Continuous Deployment - IaaS (cd-iaas.yml)"
echo "   Trigger: Merge to main branch"
echo ""
echo "   Steps:"
echo "     a) Download artifacts from CI"
echo "     b) SSH to demo server (or local execution)"
echo "     c) Pull latest Docker images"
echo "     d) docker-compose pull && docker-compose up -d"
echo "     e) Run smoke tests (curl health endpoint)"
echo "     f) Update symlink to new release"
echo "     g) Notify Slack/Discord on success/failure"
echo ""
echo "   Result: IaaS stack automatically updated"
echo "   Rollback: Previous docker-compose version kept"
echo ""

echo "3️⃣  Continuous Deployment - PaaS (cd-paas.yml)"
echo "   Trigger: Merge to main branch"
echo ""
echo "   Steps:"
echo "     a) Download artifacts from CI"
echo "     b) Lint Helm charts: helm lint"
echo "     c) Template check: helm template --validate"
echo "     d) Connect to k3s cluster (KUBECONFIG from secret)"
echo "     e) helm upgrade --install bizbuddy --wait --timeout 5m"
echo "     f) Wait for rollout: kubectl rollout status"
echo "     g) Run K8s integration tests (port-forward + curl)"
echo "     h) Notify Slack/Discord"
echo ""
echo "   Result: PaaS stack automatically updated with zero downtime"
echo "   Rollback: helm rollback <release> 1"
echo ""

echo "4️⃣  Continuous Deployment - SaaS (cd-saas.yml)"
echo "   Trigger: Manual button + Approval (GitHub Environments)"
echo ""
echo "   Steps:"
echo "     a) Manual approval required (prevents accidental prod deploy)"
echo "     b) Terraform init & plan (shown in logs)"
echo "     c) Manual approval for terraform apply"
echo "     d) terraform apply (provisions cloud infrastructure)"
echo "     e) Generate kubeconfig from terraform output"
echo "     f) Configure kubectl"
echo "     g) Deploy Helm charts to cloud cluster (EKS/GKE)"
echo "     h) Run production smoke tests"
echo "     i) Update DNS (Route53) if needed"
echo "     j) Send success notification (Slack, email)"
echo ""
echo "   Result: Full SaaS deployment to cloud"
echo "   Rollback: terraform apply -var='revert=true' OR helm rollback"
echo ""

echo "=========================================="
echo "🔐 Secrets and Configuration"
echo "=========================================="
echo ""
echo "GitHub Secrets (repository Settings → Secrets and variables → Actions):"
echo ""
echo "  GHCR_PAT               - GitHub Container Registry access token"
echo "  K3S_KUBECONFIG         - Base64 encoded kubeconfig for local k3s"
echo "  AWS_ACCESS_KEY_ID      - AWS access key (for SaaS)"
echo "  AWS_SECRET_ACCESS_KEY  - AWS secret key (for SaaS)"
echo "  SLACK_WEBHOOK_URL      - Slack notifications (optional)"
echo "  OPENAI_API_KEY         - OpenAI key (passed as env var, masked)"
echo ""
echo "All secrets are masked in logs automatically by GitHub."
echo ""

echo "=========================================="
echo "📊 Quality Gates"
echo "=========================================="
echo ""
echo "Each pipeline has automated checks:"
echo ""
echo "  ✅ TypeScript compilation"
echo "  ✅ ESLint rules (no errors)"
echo "  ✅ Jest tests (>80% coverage target)"
echo "  ✅ Build succeeds (both backend and frontend)"
echo "  ✅ Security scan: no high/critical vulnerabilities"
echo "  ✅ Health checks after deployment"
echo "  ✅ Integration tests (API endpoints respond)"
echo ""

echo "=========================================="
echo "🖥️  Demo: Viewing Workflows"
echo "=========================================="
echo ""

# Check if workflows exist
if [[ -d "$workflow_dir" ]]; then
  echo "📂 Workflows in this repository:"
  ls -1 "$workflow_dir" | sed 's/^/   • /'
  echo ""
  echo "To view workflow runs:"
  echo "  1. Go to GitHub repository"
  echo "  2. Click 'Actions' tab"
  echo "  3. Select a workflow run to see logs"
  echo ""
else
  echo "Workflows not yet created. They will appear in: $workflow_dir"
  echo "After implementation, you'll see:"
  echo "  • CI / Lint / Test"
  echo "  • Deploy IaaS"
  echo "  • Deploy PaaS"
  echo "  • Deploy SaaS"
  echo ""
fi

echo "=========================================="
echo "🎯 Demo Instructions"
echo "=========================================="
echo ""
echo "To demonstrate the CI/CD pipeline:"
echo ""
echo "1. Show the GitHub Actions tab (if workflows exist)"
echo "2. Show a completed run (green checkmark)"
echo "3. Click into a run and show:"
echo "   • Checkout, Setup Node.js, Cache steps"
echo "   • TypeScript compile step (fast)"
echo "   • Lint step (showing warnings as comments on PR)"
echo "   • Test step with coverage"
echo "   • Build steps creating Docker images"
echo "   • Deploy steps (IaaS/PaaS) or manual approval (SaaS)"
echo ""
echo "4. Show manual approval gate for SaaS:"
echo "   - Go to 'Environments' in GitHub repo settings"
echo "   - Show 'production' environment with required reviewers"
echo "   - When SaaS workflow triggers, it pauses for approval"
echo "   - Approver gets email/Slack notification"
echo "   - After approval, terraform apply runs"
echo ""
echo "5. Show notifications (if Slack/Discord configured)"
echo "   • Success message with build number and environment"
echo "   • Failure message with error logs link"
echo ""
echo "=========================================="
echo "✅ CI/CD DEMO COMPLETE"
echo "=========================================="
echo ""
echo "💡 Key takeaways:"
echo "  • Automated testing and deployment"
echo "  • Quality gates prevent bugs reaching prod"
echo "  • Manual approval for risky SaaS deployments"
echo "  • Same pipeline for IaaS, PaaS, and SaaS"
echo "  • Notifications keep team informed"
echo "  • Infrastructure as Code (Terraform) for SaaS"
echo ""
echo "Next: Review the complete architecture at deploy/README.md"
echo ""
