apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bizbuddy-frontend.fullname" . }}
  labels:
    {{- include "bizbuddy-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bizbuddy-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bizbuddy-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: {{ .Values.config.REACT_APP_API_URL | quote }}
            - name: REACT_APP_USE_SSL
              value: {{ .Values.config.REACT_APP_USE_SSL | quote }}
            - name: REACT_APP_SOCKET_URL
              value: {{ .Values.config.REACT_APP_SOCKET_URL | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
